### ISSUE TITLE
Bemerkungen des Code Reviews umsetzen

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#96]
Respektive das Code Review durchgehen und schauen, was Sinn macht.

## Tasks
- [x] Code Einrückung vereinheitlichen

- [x] Klassen dokumentieren

- [x] yml-Files Start und End-Tags Benutzung bestimmen (ist dies jetzt bereits geklärt?)

- [x] concept.md löschen

- [x] content-link.php kürzen
![content-link](https://i.imgur.com/xCsFq4U.png)
=> Ist nicht mehr vorhanden. War so im Standard-Template von WordPress

- [x] Stammdaten/TourendatenController.php kürzen
![datencontroller](https://i.imgur.com/EbObmAj.png)

- [x] inc/jugend.php Code Wiederholung entfernen
![jugend](https://i.imgur.com/up6HUam.png)

- [x] Touren/MetaBoxes/Common.php Gleichheitszeichenfehler bereinigen
![common](https://i.imgur.com/I6j4Vcg.png)

- [x] Adressverwaltung/views/includes/detail-history-edit.blade.php Typo korrigieren (Rückgängig -> rückgängig)

**Comment by dominikfankhauser** [comment]
Code Reviews durchgeschaut und Vorschläge zur Umsetzung erarbeitet.

Aufwand: 2.5 Stunden

**Comment by Niroth** [comment]
- [ ] Code Einrückung vereinheitlichen

- [ ] Klassen dokumentieren

- [ ] yml-Files Start und End-Tags Benutzung bestimmen (ist dies jetzt bereits geklärt?)

- [ ] concept.md löschen

- [ ] content-link.php kürzen
![content-link](https://i.imgur.com/xCsFq4U.png)

- [ ] Stammdaten/TourendatenController.php kürzen
![datencontroller](https://i.imgur.com/EbObmAj.png)

- [ ] inc/jugend.php Code Wiederholung entfernen
![jugend](https://i.imgur.com/up6HUam.png)

- [ ] inc/post-types.php verschönern
![post-types](https://i.imgur.com/1pYbpVp.png)

- [ ] Touren/MetaBoxes/Common.php Gleichheitszeichenfehler bereinigen
![common](https://i.imgur.com/I6j4Vcg.png)

- [ ] Adressverwaltung/views/includes/detail-history-edit.blade.php Typo korrigieren (Rückgängig -> rückgängig)

**Comment by dominikfankhauser** [comment]
Bereiche Tourenrückmeldungen und Stammdaten dokumentiert.

Aufwand: 3 Stunden

**Comment by Niroth** [comment]
Typo und TourendatenController angepasst.

Aufwand: 1 Stunde

**Comment by ilcoron** [comment]
Aufwand: 0.5 Stunden
